/**
 * @core/branches — branch identity, id scheme, and wire schemas shared by the
 * server, the admin client, and the collab engine. Barrel-gated: import ONLY
 * from `@core/branches` outside this folder.
 */
export {
  BRANCH_ID_PATTERN,
  BRANCH_NAME_MAX_LENGTH,
  MAIN_BRANCH_ID,
  SITE_SHELL_LOGICAL_ID,
  isMainBranch,
  isValidBranchId,
  logicalIdOf,
  physicalId,
  slugifyBranchName,
} from './ids'
export { canActOnBranch, canMergeBranches } from './access'
export { mergeJson } from './threeWayMerge'
export {
  BranchEnvelopeSchema,
  BranchListEnvelopeSchema,
  BranchPreviewLinkEnvelopeSchema,
  BranchPreviewStateEnvelopeSchema,
  CreateBranchBodySchema,
  RenameBranchBodySchema,
  ApplyMergeBodySchema,
  ApplyMergeEnvelopeSchema,
  UndoMergeEnvelopeSchema,
  MergeChangeSchema,
  BranchReviewStateSchema,
  CreateMergeRequestBodySchema,
  CreateReviewCommentBodySchema,
  DeclineMergeRequestBodySchema,
  MergeRequestEnvelopeSchema,
  ReviewCommentEnvelopeSchema,
  REVIEW_VIEWPORT,
  MergePlanEnvelopeSchema,
  type ApplyMergeBody,
  type ApplyMergeEnvelope,
  type BranchMergeRecord,
  type UndoMergeEnvelope,
  type BranchPreview,
  type CreateBranchBody,
  type MergeChange,
  type MergeChangeDetail,
  type MergeEntityKind,
  type MergeFieldChange,
  type MergeTreeDiff,
  type MergeSchemaField,
  type BranchMergeRequest,
  type BranchReviewComment,
  type BranchReviewState,
  type CreateReviewCommentBody,
  type MergeRequestStatus,
  type ReviewRenderSide,
  type ReviewUserLabel,
  type MergeDirection,
  type MergePlan,
  type MergeResolution,
  type RenameBranchBody,
  type SiteBranch,
} from './schemas'
